version: '3.8'

services:
  printarex-frontend:
    build: .
    ports:
      - "5173:80"
    container_name: printarex-frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

